from sqlalchemy import Column, Integer, String, Float, Boolean, Date, DateTime, ForeignKey
from sqlalchemy.orm import relationship
from Database import Base

class Season(Base):
    __tablename__ = 'seasons'
    season_id = Column(Integer, primary_key=True, autoincrement=False)
    season = Column(String(9))
    team_seasons = relationship("TeamSeason", back_populates="season", passive_deletes=True)
    player_seasons = relationship("PlayerSeason", back_populates="season", passive_deletes=True)
    matches = relationship("Match", back_populates="season", passive_deletes=True)

class Team(Base):
    __tablename__ = 'teams'
    team_id = Column(Integer, primary_key=True, autoincrement=False)
    name = Column(String(45))
    logo = Column(String(255))
    team_seasons = relationship("TeamSeason", back_populates="team", passive_deletes=True)
    player_seasons = relationship("PlayerSeason", back_populates="team", passive_deletes=True)
    home_matches = relationship("Match", back_populates="home_team", foreign_keys="Match.home_team_id", passive_deletes=True)
    away_matches = relationship("Match", back_populates="away_team", foreign_keys="Match.away_team_id", passive_deletes=True)

class Nation(Base):
    __tablename__ = 'nations'
    nation_id = Column(Integer, primary_key=True)
    nation_name = Column(String(45))
    players = relationship("Player", back_populates="nation", passive_deletes=True)

class Referee(Base):
    __tablename__ = 'referees'
    referee_id = Column(Integer, primary_key=True)
    name = Column(String(45))
    matches = relationship("Match", back_populates="referee")

class Player(Base):
    __tablename__ = 'players'
    player_id = Column(Integer, primary_key=True, autoincrement=False)
    name = Column(String(100))
    age = Column(Integer, nullable=True)
    nation_id = Column(Integer, ForeignKey('nations.nation_id', ondelete="CASCADE"), nullable=True)
    height_in_m = Column(Float, nullable=True)
    weight = Column(Integer, nullable=True)
    date_of_birth = Column(Date, nullable=True)
    foot = Column(String(5), nullable=True)
    nation = relationship("Nation", back_populates="players")
    player_seasons = relationship("PlayerSeason", back_populates="player", passive_deletes=True)

class TeamSeason(Base):
    __tablename__ = "teams_has_seasons"
    team_id = Column(Integer, ForeignKey("teams.team_id", ondelete="CASCADE"), primary_key=True)
    season_id = Column(Integer, ForeignKey("seasons.season_id", ondelete="CASCADE"), primary_key=True)
    form = Column(String)
    fixtures_played_home = Column(Integer)
    fixtures_played_away = Column(Integer)
    fixtures_wins_home = Column(Integer)
    fixtures_wins_away = Column(Integer)
    fixtures_draws_home = Column(Integer)
    fixtures_draws_away = Column(Integer)
    fixtures_loses_home = Column(Integer)
    fixtures_loses_away = Column(Integer)
    goals_for_total_home = Column(Integer)
    goals_for_total_away = Column(Integer)
    goals_for_minute_0_15_total = Column(Integer)
    goals_for_minute_0_15_percentage = Column(Float)
    goals_for_minute_16_30_total = Column(Integer)
    goals_for_minute_16_30_percentage = Column(Float)
    goals_for_minute_31_45_total = Column(Integer)
    goals_for_minute_31_45_percentage = Column(Float)
    goals_for_minute_46_60_total = Column(Integer)
    goals_for_minute_46_60_percentage = Column(Float)
    goals_for_minute_61_75_total = Column(Integer)
    goals_for_minute_61_75_percentage = Column(Float)
    goals_for_minute_76_90_total = Column(Integer)
    goals_for_minute_76_90_percentage = Column(Float)
    goals_for_minute_91_105_total = Column(Integer)
    goals_for_minute_91_105_percentage = Column(Float)
    goals_for_minute_106_120_total = Column(Integer)
    goals_for_minute_106_120_percentage = Column(Float)
    goals_against_total_home = Column(Integer)
    goals_against_total_away = Column(Integer)
    goals_against_average_home = Column(Float)
    goals_against_average_away = Column(Float)
    goals_against_minute_0_15_total = Column(Integer)
    goals_against_minute_0_15_percentage = Column(Float)
    goals_against_minute_16_30_total = Column(Integer)
    goals_against_minute_16_30_percentage = Column(Float)
    goals_against_minute_31_45_total = Column(Integer)
    goals_against_minute_31_45_percentage = Column(Float)
    goals_against_minute_46_60_total = Column(Integer)
    goals_against_minute_46_60_percentage = Column(Float)
    goals_against_minute_61_75_total = Column(Integer)
    goals_against_minute_61_75_percentage = Column(Float)
    goals_against_minute_76_90_total = Column(Integer)
    goals_against_minute_76_90_percentage = Column(Float)
    goals_against_minute_91_105_total = Column(Integer)
    goals_against_minute_91_105_percentage = Column(Float)
    goals_against_minute_106_120_total = Column(Integer)
    goals_against_minute_106_120_percentage = Column(Float)
    biggest_streak_wins = Column(String)
    biggest_streak_draws = Column(String)
    biggest_streak_loses = Column(String)
    biggest_wins_home = Column(String)
    biggest_wins_away = Column(String)
    biggest_loses_home = Column(String)
    biggest_loses_away = Column(String)
    biggest_goals_for_home = Column(String)
    biggest_goals_for_away = Column(String)
    biggest_goals_against_home = Column(String)
    biggest_goals_against_away = Column(String)
    clean_sheet_home = Column(Integer)
    clean_sheet_away = Column(Integer)
    failed_to_score_home = Column(Integer)
    failed_to_score_away = Column(Integer)
    penalty_scored_total = Column(Integer)
    penalty_missed_total = Column(Integer)
    lineups = Column(String)
    cards_yellow_0_15_total = Column(Integer)
    cards_yellow_0_15_percentage = Column(Float)
    cards_yellow_16_30_total = Column(Integer)
    cards_yellow_16_30_percentage = Column(Float)
    cards_yellow_31_45_total = Column(Integer)
    cards_yellow_31_45_percentage = Column(Float)
    cards_yellow_46_60_total = Column(Integer)
    cards_yellow_46_60_percentage = Column(Float)
    cards_yellow_61_75_total = Column(Integer)
    cards_yellow_61_75_percentage = Column(Float)
    cards_yellow_76_90_total = Column(Integer)
    cards_yellow_76_90_percentage = Column(Float)
    cards_yellow_91_105_total = Column(Integer)
    cards_yellow_91_105_percentage = Column(Float)
    cards_red_0_15_total = Column(Integer)
    cards_red_0_15_percentage = Column(Float)
    cards_red_16_30_total = Column(Integer)
    cards_red_16_30_percentage = Column(Float)
    cards_red_31_45_total = Column(Integer)
    cards_red_31_45_percentage = Column(Float)
    cards_red_46_60_total = Column(Integer)
    cards_red_46_60_percentage = Column(Float)
    cards_red_61_75_total = Column(Integer)
    cards_red_61_75_percentage = Column(Float)
    cards_red_76_90_total = Column(Integer)
    cards_red_76_90_percentage = Column(Float)
    cards_red_91_105_total = Column(Integer)
    cards_red_91_105_percentage = Column(Float)
    cards_red_106_120_total = Column(Integer)
    cards_red_106_120_percentage = Column(Float)
    team = relationship("Team", back_populates="team_seasons")
    season = relationship("Season", back_populates="team_seasons")

class PlayerSeason(Base):
    __tablename__ = "players_has_seasons"
    player_id = Column(Integer, ForeignKey("players.player_id", ondelete="CASCADE"), primary_key=True)
    season_id = Column(Integer, ForeignKey("seasons.season_id", ondelete="CASCADE"), primary_key=True)
    team_id = Column(Integer, ForeignKey("teams.team_id", ondelete="CASCADE"), primary_key=True)
    market_value = Column(String(45), nullable=True)
    position = Column(String(45), nullable=True)
    games_appearences = Column(Integer)
    games_lineups = Column(Integer)
    games_minutes = Column(Integer)
    games_number = Column(Integer)
    games_position = Column(String)
    games_rating = Column(Float)
    games_captain = Column(String)
    substitutes_in = Column(Integer)
    substitutes_out = Column(Integer)
    substitutes_bench = Column(Integer)
    shots_total = Column(Integer)
    shots_on = Column(Integer)
    goals_total = Column(Integer)
    goals_conceded = Column(Integer)
    goals_assists = Column(Integer)
    goals_saves = Column(Integer)
    passes_total = Column(Integer)
    passes_key = Column(Integer)
    passes_accuracy = Column(Integer)
    tackles_total = Column(Integer)
    tackles_blocks = Column(Integer)
    tackles_interceptions = Column(Integer)
    duels_total = Column(Integer)
    duels_won = Column(Integer)
    dribbles_attempts = Column(Integer)
    dribbles_success = Column(Integer)
    dribbles_past = Column(Integer)
    fouls_drawn = Column(Integer)
    fouls_committed = Column(Integer)
    cards_yellow = Column(Integer)
    cards_yellowred = Column(Integer)
    cards_red = Column(Integer)
    penalty_won = Column(Integer)
    penalty_commited = Column(Integer)
    penalty_scored = Column(Integer)
    penalty_missed = Column(Integer)
    penalty_saved = Column(Integer)
    player = relationship("Player", back_populates="player_seasons")
    season = relationship("Season", back_populates="player_seasons")
    team = relationship("Team", back_populates="player_seasons")

class Match(Base):
    __tablename__ = "all_matches"
    fixture_id = Column(Integer, primary_key=True, autoincrement=False)
    referee_id = Column(Integer, ForeignKey("referees.referee_id"), nullable=True)
    season_id = Column(Integer, ForeignKey("seasons.season_id", ondelete="CASCADE"))
    home_team_id = Column(Integer, ForeignKey("teams.team_id", ondelete="CASCADE"))
    away_team_id = Column(Integer, ForeignKey("teams.team_id", ondelete="CASCADE"))
    fixture_timezone = Column(String)
    fixture_date = Column(String)
    fixture_timestamp = Column(Integer)
    fixture_periods_first = Column(Integer)
    fixture_periods_second = Column(Integer)
    fixture_venue_id = Column(Integer)
    fixture_venue_name = Column(String)
    fixture_venue_city = Column(String)
    fixture_status_long = Column(String)
    fixture_status_short = Column(String)
    fixture_status_elapsed = Column(Integer)
    fixture_status_extra = Column(Integer)
    league_id = Column(Integer)
    league_name = Column(String)
    league_country = Column(String)
    league_logo = Column(String)
    league_flag = Column(String)
    league_round = Column(String)
    league_standings = Column(Boolean)
    teams_home_name = Column(String)
    teams_home_logo = Column(String)
    teams_home_winner = Column(Boolean)
    teams_away_name = Column(String)
    teams_away_logo = Column(String)
    teams_away_winner = Column(Boolean)
    goals_home = Column(Integer)
    goals_away = Column(Integer)
    score_halftime_home = Column(Integer)
    score_halftime_away = Column(Integer)
    score_fulltime_home = Column(Integer)
    score_fulltime_away = Column(Integer)
    score_extratime_home = Column(Integer)
    score_extratime_away = Column(Integer)
    score_penalty_home = Column(Integer)
    score_penalty_away = Column(Integer)
    referee = relationship("Referee", back_populates="matches")
    season = relationship("Season", back_populates="matches")
    home_team = relationship("Team", foreign_keys=[home_team_id], back_populates="home_matches")
    away_team = relationship("Team", foreign_keys=[away_team_id], back_populates="away_matches")

class Users(Base):
    __tablename__ = "users"
    user_id = Column(Integer, primary_key=True, autoincrement=True)
    username = Column(String(50), unique=True, nullable=False)